problem1 = "Tell me what animals are in the picture and generate another picture with the same kinds of animals but in a Monet style."
problem2 = "Based on a photo of my dinner table with prepared food, write a dinner invitation to Jane to invite her to my home for dinner. You can describe what food is already set for her."
problem3 = "Who are the famous people in the picture are and tell me something interesting or important about them."
problem4 = "For the problem in the input picture, please use markdown to express it and then give me an answer."
problem5 = "Can you tell me where is this place in the picture and generate some traveling advice if I go there sometime."
problem6 = "Generate a short story about a hero taking an adventure in the forest and encountering a dragon. Then generate a picture based on the story script."